services:
  backend-antiginx:
    build: 
      context: .
      dockerfile: Dockerfile

    container_name: backend-antiginx
    restart: unless-stopped

    ports:
      - "${BACKEND_PORT}:8080"

    env_file:
      - .env

    mem_limit: 2048m