services:
  backend-antiginx:
    image: ghcr.io/prawo-i-piesc/backend-antiginx:latest

    container_name: backend
    restart: unless-stopped

    ports:
      - "${BACKEND_PORT}:8080"

    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}

    mem_limit: 2048m

    networks:
      - vpn-net

networks:
  vpn-net:
    external: true